### PR TITLE
Html, Css and Linters

### PR DESCRIPTION
**Pull request by Agape-nduwamungu**
Ensured:
- that the README.md is descriptive enough.
- that the .html file and .css file are seen.
- that the linters are well-configured and running properly.

### CODE REVIEW

**Review by mckent05 — CHANGES_REQUESTED** [review]
Hi @Agape-nduwamungu, 

# STATUS: CHANGES REQUIRED ♻️ ♻️ 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
almost there

## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👍 👍 


## Required Changes ♻️
- Please note that in your future Microverse Projects, when working on a new milestone, do not push commits into the master branch, all commits should be pushed into the feature branch, so code reviewers can view the changes made in the PR and give you comprehensive feedback 😄 
- According to the project requirements, the `test.md` file should be ignored by git. I can still see this file in your repo, please fix this 🙏 
- As a developer, it is very important that your project has a professional readme, this would help users understand better what your project is all about. I suggest that you use the [microverse readme](https://github.com/microverseinc/readme-template) template and ensure all required sections are present in your readme, your readme is missing most of the required sections, and also do not forget to customize your readme to fit each project you are working on. Please fix this 👍 
- Your linters are not running, this is probably because you have not properly set up your [linters config](https://github.com/microverseinc/linters-config), remember that linters help us ensure that we write code that is clean and easy to maintain. Please ensure all linter checks are running and passing 🙏 
- To help make your repo more professional, it is important that your PR has a descriptive PR title and PR summary. Your PR title should give a brief summary of what the PR is all about, while your PR description explains in a little more detail the changes made in that R. Please fix this 👍 
To edit your PR title, open your PR and click on the 'edit' button, reference the picture attached below:
rgwrgwg

To edit your PR sumary, open your PR and click on the button, reference the picture attached below:
fwhaeth
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Agape-nduwamungu** [comment]
Added the missing linter config files to the branch.
Checking if the linters are now working properly.

**Comment by Agape-nduwamungu** [comment]
Added a more descriptive README.md file in the main branch.

**Comment by Agape-nduwamungu** [comment]
Made changes to the test.md file that was supposed to be ignored by git.

**Review by GedeonTS — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED :recycle: :
Hi @Agape-nduwamungu , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



 ## Highlights :tophat: :+1: 
- [x] No linter errors :+1: 
- [x] Good use of GitHub flow :+1: 

 ## Required Changes ♻️
- As requested by the previous reviewer, kindly make sure test.md is not seen in github: for that you have just to add a line test.md in .gitignore
- As suggested by the previous reviewer kindly make sure all the sections of the README [template](https://github.com/microverseinc/readme-template) are present in yours, the only optional section is FAQ
- It would be better to add a title to your PR description as requested and explained [here](https://github.com/Agape-nduwamungu/hello_microverse_project/pull/2#:~:text=To%20help%20make,click%20on%20the) by the previous reviewer :recycle: 
_Check the comments under the review._

## Optional suggestions :ringed_planet: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Tufahel — CHANGES_REQUESTED** [review]
# Status: Required Changes :recycle:
Hi @Agape-nduwamungu   :wave: 

Well done on implementing some of the required changes. :+1:  
You still need to fix some issues before moving to the next project. :running_man: 

## Highlights 🌟

Alt Text

✔️ Linters checks are passing
✔️ Use GitHub Flow
✔️ Meaningful commit messages.

## Required Changes ♻️

- [ ] Kindly add the line `test.md`  in `.gitignore` file to ignore the `test.md` file in your repository. As per the [project requirement](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md), there should not be any `test.md` file in the repository.
  - ***Your repository looks like***
  image
  - ***Project requirement***
  image

- [ ] Kindly add everything from this [readme template](https://github.com/microverseinc/readme-template/blob/master/README.md) to your Readme as per previous reviewers suggestion.
   - While copying the `readme template`, kindly ignore the `Micorverse` logo on the top of the readme.
   - You can skip the `FAQ` option of the `readme template` if you want.


_Please kindly check the comments under the review._

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Agape-nduwamungu** [comment]
Added some files to the features branch.
Modified the README.md file.

**Review by wayungi — APPROVED** [review]
H @Agape-nduwamungu , 

Good work implementing all the changes requested by the previous reviewer. Its now time to celebrate.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

image


## Highlights
- [ ] Profesional README ✔️ 
- [ ] All linter checks passing ✔️ 
- [ ] Good commit messages ✔️ 
- [ ] No merge conflicts ✔️ 
- [ ]  Correct GitHub flow ✔️ 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ichala — COMMENTED** [review]
Hi Student  ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
 
68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966

# To Highlight 💪🏻

- Project Already Approved ✔️ 


 Good job implementing the requirements  :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Optional Suggestions  :

- N/A


**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
